CivicsTest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='cards:index')),
    path('cards/', include('cards.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cards/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from . import views

app_name = 'cards'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path(
        '<int:question_list_id>/update-questions-list',
        views.update_questions_list,
        name='update-questions-list'
    ),
    path(
        'prefilled-update',
        views.update_questions_list_prefilled,
        name='update-questions-list-prefilled'
    ),


]

cards/models.py
import datetime

from django.contrib import admin
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=2000, default='')
    question_text.verbose_name = 'question'
    question_number = models.IntegerField(default=0)
    question_number.verbose_name = '#'
    pub_date = models.DateTimeField('date published')
    question_group = models.CharField(max_length=600, default='')
    question_group.verbose_name = 'group'
    question_group_title = models.CharField(max_length=600, default='')
    question_group_title.verbose_name = 'series'

    def __str__(self):
        return self.question_text

    # noinspection PyTypeChecker
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=2000, default='')
    answer_correct = models.BooleanField(True)
    answer_correct.verbose_name = 'Correct Answer'

    def __str__(self):
        return self.answer_text

    def is_correct(self):
        return self.answer_correct.get_prep_value


class QuestionsUpdate(models.Model):
    file = models.FileField(upload_to='cards/uploads')
    file_name = models.CharField(max_length=200, default='')
    file_description = models.CharField(max_length=2000, default='')

    def __str__(self):
        return self.file_name

cards/views.py
import os
from pathlib import Path
from random import shuffle

from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.core.paginator import Paginator
from django.db import transaction
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Question, QuestionsUpdate
from .questionsupdater import QuestionsUpdater


class IndexView(generic.ListView):
    template_name = 'cards/index.html'
    paginate_by = "5"

    def get_queryset(self):
        questions_all = []

        [questions_all.append(i) for i in list(Question.objects.all().order_by('question_number'))]

        get_request = self.request.GET

        if not self.request.session.session_key:
            self.request.session.create()
        self.request.session.set_expiry(864000)

        # in case DB changed when user has an active session
        if len(self.request.session.get('order', list(range(0, len(questions_all))))) != len(questions_all):
            for key in list(self.request.session.keys()):
                if not key.startswith("_"):  # skip keys set by the django system
                    del self.request.session[key]
            self.request.session.modified = True
            return questions_all

        if get_request.get('order'):
            self.request.session['mix_order'] = (False if get_request.get('order').__eq__("straight") else True)
            self.request.session['order_changed'] = True
        else:
            self.request.session['mix_order'] = self.request.session.get('mix_order', False)
            self.request.session['order_changed'] = False

        if len(get_request) > 0:
            self.request.session['refresh'] = True
            self.request.session['current_page'] = (get_request.get('page') if get_request.get('page') else 1)
        else:
            self.request.session['refresh'] = False
            self.request.session['current_page'] = self.request.session.get('current_page', 1)

        group_current = self.request.session.get('current_group', "All")
        if get_request.get('question-group'):
            self.request.session['group_changed'] = True
            self.request.session['current_group'] = get_request.get('question-group')
            self.request.session['current_page'] = 1
        else:
            self.request.session['group_changed'] = False
            self.request.session['current_group'] = group_current
            self.request.session['current_page'] = self.request.session.get('current_page', 1)

        self.request.session['num_objects'] = (get_request.get('num-objects') if get_request.get('num-objects')
                                               else self.request.session.get('num_objects', self.paginate_by))

        if self.request.session.get('order_changed', False):
            if self.request.session.get('mix_order', False):
                mix_order = list(range(0, len(questions_all)))
                shuffle(mix_order)
                self.request.session['order'] = mix_order
            else:
                self.request.session['order'] = list(range(0, len(questions_all)))
        else:
            self.request.session['order'] = self.request.session.get('order', list(range(0, len(questions_all))))

        questions_for_return_all = []
        [questions_for_return_all.append(questions_all[i]) for i in
         self.request.session.get('order', list(range(0, len(questions_all))))]

        if group_current.__eq__("All"):
            return questions_for_return_all
        else:
            questions_for_return = []
            for q in questions_for_return_all:
                if q.question_group.__eq__(group_current):
                    questions_for_return.append(q)
            return questions_for_return

    def get_context_data(self, **kwargs):

        context = super(IndexView, self).get_context_data(**kwargs)

        context['current_group'] = self.request.session.get('current_group', "All")

        groups_list = list(Question.objects.values_list('question_group', flat=True).distinct())
        groups_list.insert(0, "All")
        context['groups_list'] = groups_list

        page = self.request.session.get('current_page', 1)

        paginate_by_user = self.request.session.get('num_objects', self.paginate_by)

        context['num_objects'] = paginate_by_user

        context['num_objects_array'] = ["5", "10", "20", "All"]

        context['mix_order'] = self.request.session.get('mix_order', False)

        context['refresh'] = self.request.session.get('refresh', False)

        if paginate_by_user.__eq__("All"):
            context['latest_question_list'] = self.get_queryset()
        else:
            paginator = Paginator(self.get_queryset(), int(paginate_by_user))
            context['latest_question_list'] = paginator.get_page(page)

        return context


@staff_member_required
def update_questions_list(request, *args, **kwargs):
    file_path = QuestionsUpdate.objects.get(id=kwargs["question_list_id"]).file.path
    if not os.path.isfile(file_path):
        messages.add_message(request, messages.INFO, 'Could not load the prefilled questions. Click to dismiss.')
        return HttpResponseRedirect(reverse('admin:cards_questionsupdate_changelist', args=(), current_app='cards'))
    replace_all_questions(file_path)
    messages.add_message(request, messages.INFO, 'The questions have been replaced. Click to dismiss.')
    return HttpResponseRedirect(reverse('cards:index', args=(), current_app='cards'))


def update_questions_list_prefilled(request):
    root_dir = Path(__file__).resolve().parent.parent
    file_path = os.path.join(root_dir, 'media', 'cards', 'uploads', 'CivicsQuestions2008.txt')
    if not os.path.isfile(file_path):
        messages.add_message(request, messages.INFO, 'Could not load the prefilled questions. Click to dismiss.')
        return HttpResponseRedirect(reverse('cards:index', args=(), current_app='cards'))
    replace_all_questions(file_path)
    return HttpResponseRedirect(reverse('cards:index', args=(), current_app='cards'))


def replace_all_questions(file_path):
    # wiping all the existing questions
    with transaction.atomic():
        for q_object in Question.objects.all():
            q_object.delete()

    # creating new questions and answers
    questions_new = QuestionsUpdater(file_path).questions
    questions_new.reverse()
    with transaction.atomic():
        for q in questions_new:
            question = Question(question_text=q.question_text, question_number=q.question_id,
                                pub_date=timezone.now(),
                                question_group=q.question_group, question_group_title=q.question_group_title)
            question.save()
            for count, value in enumerate(q.answer_text):
                question.answer_set.create(answer_text=value, answer_correct=q.answer_correct[count]).save()

cards/templates/cards/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% if refresh %}
        <meta http-equiv="refresh" content="0; URL=/" />
    {% endif %}
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cards</title>
    <link rel="shortcut icon" href="{% static 'cards/favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'cards/style.css' %}">
    <script src="{% static 'cards/app.js' %}"></script>
</head>
<body onload="removeHover()">


{% if latest_question_list %}

<div class="header">
    {% for group in groups_list %}
    <div class="group-link-container">
        <a class="group-link{% ifequal current_group group %} highlighted{% endifequal %}"
           href="?question-group={{ group }}">{{ group }}</a>
    </div>
    {% endfor %}
</div>

{% for message in messages %}
<br>
    <div class="header notice">
      <p><a href="/" class="notice-link group-link">{{ message }}</a></p>
    </div>
{% endfor %}

<div class="cards_container">
    <div class="cards hover-effect">

        {% for question in latest_question_list %}

        <div class="center">
            <div id="{{ question.question_number }}" onclick="active_switch('{{ question.question_number }}')" class="property-card">
                <div class="property-image"
                     style="background-image:url('{% static 'cards/img' %}/{{ question.question_group|slice:5|slugify }}.png')">
                    <div class="property-image-title">
                        <ul class="answer-ul">
                            {% for answer in question.answer_set.all %}
                            {% if answer.answer_correct %}
                            <li>{{ answer.answer_text }}</li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="property-description">
                    <p> {{ question.question_group }} </p>
                    <h5>{{ question.question_text }}</h5>
                </div>
                <div class="property-question-number">
                    <div class="question-number"><h5>{{ question.question_number }}</h5></div>
                </div>
            </div>
        </div>

        {% endfor %}

    </div>
</div>


<div class="footer">

    <div class="pagination">
        <span class="step-links ">
            {% if latest_question_list.has_previous %}
                <a class="group-link" href="?page=1">&laquo; first</a>
                <a class="group-link"
                   href="?page={{ latest_question_list.previous_page_number }}">prev</a>
            {% endif %}
            {% if latest_question_list.has_previous and latest_question_list.has_next %}
                 <span class="group-link"> {{ latest_question_list.number }} / {{ latest_question_list.paginator.num_pages }}</span>
            {% elif latest_question_list.paginator.num_pages %}
                 <span class="group-link">Page {{ latest_question_list.number }} of {{ latest_question_list.paginator.num_pages }}</span>
            {% endif %}
            {% if latest_question_list.has_next %}
                <a class="group-link"
                   href="?page={{ latest_question_list.next_page_number }}">next</a>
                <a class="group-link"
                   href="?page={{ latest_question_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>


    <div class="pagination">
        {% for i in num_objects_array %}
        <a class="group-link{% ifequal num_objects i %} highlighted{% endifequal %}"
           href="?num-objects={{ i }}">{{ i }}</a>
        {% endfor %}

        <a class="group-link{% if mix_order %} highlighted-mix-button{% endif %} separator"
           href="?next={{ currentUrl }}&order=mix">MIX</a>
        <a class="group-link{% if not mix_order %} highlighted{% endif %}"
           href="?order=straight">SORT</a>
    </div>
</div>


{% else %}
<div class="header notice" >
    <h2>No cards are available.</h2>
    <p>Add cards through the <a class="notice-link" href="/admin">Admin console</a> manually or Upload the questions list from USCIS.</p>
    <p>Questions update in text-only format can be found on the official USCIS web page:</p>
    <p><a class="notice-link" href="https://www.uscis.gov/citizenship/find-study-materials-and-resources/study-for-the-test">Official USCIS questions list</a></p>
    <p>And uploaded through the admin part of the website.</p>

    <a class="notice-link" href="{% url 'cards:update-questions-list-prefilled' %}">
        Click here to use prefilled questions and answers from the 2008 version of the civics test</a>

    {% for message in messages %}
      <p><a href="/" class="group-link">{{ message }}</a></p>
    {% endfor %}

</div>


{% endif %}



</body>
</html>